### PR TITLE
🐛 Fixed non-working of app on Unauthorized errors

### LINKED ISSUE #69: App does not work when deleting the API token
When deleting the API token that the app is currently using via the Traewelling website, the app stops working (does not display any data anymore). One also can't refresh the token or logout via the app anymore, the only solution is to delete the app data

### PR DESCRIPTION
**Pull request by jheubuch**
This PR fixes #69 and adds
- interceptors for API Unauthorized errors
- an event bus which can be used in future for extended communication between components

When the API responds with 401 (or 200 with login page, true story), an event will be triggered and the user will be logged out in the app.

### CODE REVIEW

File: app/src/main/java/de/hbch/traewelling/events/UnauthorizedEvent.kt [hunk 1]
```diff
@@ -0,0 +1,5 @@
+package de.hbch.traewelling.events
+
+class UnauthorizedEvent {
+
+}
```
Comment (DRSchlaubi) [inline app/src/main/java/de/hbch/traewelling/events/UnauthorizedEvent.kt:5]:
```suggestion
class UnauthorizedEvent
```

**Review by DRSchlaubi — APPROVED** [review]
